---
- name: Unsafe string demo
  hosts: localhost
  vars_prompt:
    - name: unsafe_string
      prompt: Provide some data
      private: false
      unsafe: true

  tasks:
    - name: Create a file containing the user input
      copy:
        content: "{{ unsafe_string }}"
        dest: /tmp/demofile